### ISSUE TITLE
I tried to send a win32 SendMessage with a boost::tuples::tuple variable pointed by the lParam of the message. It does not work. When doing the same with a std::tuple it does works. Can anybody explain me why?

### ISSUE THREAD

**Issue by klasing** [boostorg/tuple#16]

**Comment by djowel** [comment]
Please post an MVCE

**Comment by klasing** [comment]
First, MVCE stands for Microsoft Visual C++ Example??? Second, I'm not so sure anymore the problem, I described, had to do with boost::tuples::tuple. As far as I know I'm now sending (boost) tuples within Win32 Messages, pointed by LPARAM, without any trouble. I would have to go through my codebase to find a proof of it. But this is not worth the effort, considering all the other things I have to do. Anyway, thanks for your reply!!! greetz
